### ISSUE TITLE
Custom Dataset issue (in styleGAN2 model network)

### ISSUE THREAD

**Issue by danny0628** [chkimmmmm/StyleGAN2_MNIST#1]
Hello Kim!!
When training with custom .png image, the following error occurs. (But, this network still activate MNIST dataset)

>   File "/home/mjkim1/workspace/fl_learning/flower/model.py", line 208, in forward
    x = self.smooth(x)
  File "/home/mjkim1/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mjkim1/workspace/fl_learning/flower/model.py", line 227, in forward
    b, c, h, w = x.shape
ValueError: not enough values to unpack (expected 4, got 3)

And, model.py, line 227 code as follows
```
class Smooth(nn.Module):
    """
    Blur each channel
    """

    def __init__(self):
        super().__init__()
        kernel = [[1, 2, 1], [2, 4, 2], [1, 2, 1]]  # define the blue kernel
        kernel = torch.tensor([[kernel]], dtype=torch.float32)  # making it a pytorch tensor

        kernel /= kernel.sum()  # Normalize the kernel
        self.kernel = nn.Parameter(kernel, requires_grad=False)  # fix the kernel so it doesn't get update
        self.pad = nn.ReplicationPad2d(1)  # pad the kernel

    def forward(self, x):
        b, c, h, w = x.shape
        x = x.view(-1, 1, h, w)  # reshape
        x = self.pad(x)  # pad
        x = F.conv2d(x, self.kernel)  # smooth
        return x.view(b, c, h, w)  # reshape back and return
```

**Comment by chkimmmmm** [comment]
Hello.
You need to check the dimension of x.
The error is pointing out that your tensor 'x' cannot be reshaped to batch, C, H ,W dimensions.
Please check shape of x. 
Thanks.
